import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/Card';
import { Info, Palette, ShieldCheck } from 'lucide-react';

export default function AboutPage() {
  const seed = process.env.ASSIGNMENT_SEED || 'SEED_NOT_FOUND';

  return (
    <section className="max-w-4xl mx-auto">
      <Card>
        <CardHeader>
          <div className="flex items-center gap-3">
            <Info className="h-6 w-6" />
            <CardTitle className="text-3xl">About This Project</CardTitle>
          </div>
        </CardHeader>
        <CardContent>
          <p className="text-muted-foreground mb-6">
            This reselling marketplace is a frontend application developed for
            the Web Development Wing selection process. It is built with
            Next.js, Tailwind CSS, and Zustand for state management, and it
            communicates with a custom-built backend API.
          </p>

          <Card className="bg-muted/50">
            <CardHeader>
              <div className="flex items-center gap-3">
                <ShieldCheck className="h-5 w-5 text-primary" />
                <CardTitle className="text-xl">
                  Assignment Uniqueness Verification
                </CardTitle>
              </div>
            </CardHeader>
            <CardContent>
              <p className="text-muted-foreground mb-4">
                To ensure the authenticity and originality of this submission,
                the following unique assignment seed is used to dynamically
                generate parts of the application's theme, such as the accent
                color.
              </p>
              <div className="bg-background rounded-md p-4 text-center border">
                <span className="font-mono text-lg accent-text font-bold tracking-wider">
                  {seed}
                </span>
              </div>

              <div className="mt-6">
                <h3 className="font-semibold text-foreground flex items-center gap-2">
                  <Palette className="h-4 w-4" />
                  Theme Color Generated by Seed:
                </h3>
                <div className="w-full h-10 mt-2 rounded-md accent-bg border-2 accent-border"></div>
              </div>
            </CardContent>
          </Card>
        </CardContent>
      </Card>
    </section>
  );
}
